pipeline:
  name: docker-build
  identifier: dockerbuild
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: gitupdated
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: aws
                    region: us-east-1
                    account: "518616560215"
                    imageName: test
                    tags:
                      - latest
          caching:
            enabled: false
            paths: []
  properties:
    ci:
      codebase:
        connectorRef: gitupdated
        build: <+input>
