pipeline:
  name: local-test
  identifier: localtest
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: gitupdated
                    privileged: false
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo hello
                      cd ci-cd/
                      pwd
                      ls
                      mvn clean
                      mvn package
                      pwd
                      ls
                      cd target/
                      ls
                      pwd
              - step:
                  type: S3Upload
                  name: S3Upload_2
                  identifier: S3Upload_2
                  spec:
                    connectorRef: aws
                    region: us-east-1
                    bucket: harman-primetime-temp-staging
                    sourcePath: ci-cd/target
          caching:
            enabled: false
            paths: []
        delegateSelectors:
          - docker-delegate
