pipeline:
  name: testing
  identifier: testing
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo hello
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: gitupdated
                    build:
                      type: branch
                      spec:
                        branch: main
          caching:
            enabled: false
            paths: []
        when:
          pipelineStatus: Success
        delegateSelectors:
          - linux-amd64
