pipeline:
  name: testing
  identifier: testing
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        template:
          templateRef: firstmavenbuild
          versionLabel: "1.0"
  properties:
    ci:
      codebase:
        connectorRef: gitupdated
        build: <+input>
